-- Phase F.1 — User-uploaded place photos: state lifecycle, perceptual-hash
-- denylist, and DSA appeal audit log. Two storage buckets are also created:
--
--   * place-photos-quarantine — service-role only. Initial landing zone for
--     every upload until moderation completes.
--   * place-photos-public     — anon read. Promoted-only assets, served by
--     CDN. Each object's storage_path is `<city_place_id>/<photo_id>.jpg`.
--
-- Section 7.3 of the places-cost-and-owned-data plan defines the schema.
-- Section 7.4 defines the lifecycle the `status` column tracks.
-- Section 7.1 describes the threats this audit log mitigates.

-- ---------------------------------------------------------------------------
-- place_user_photos
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.place_user_photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  city_place_id uuid NOT NULL REFERENCES public.city_places (id) ON DELETE CASCADE,
  uploader_user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  -- starts in the quarantine bucket; rewritten on promotion
  storage_path text NOT NULL,
  public_url text,
  status text NOT NULL DEFAULT 'pending_moderation' CHECK (status IN (
    'pending_moderation',
    'approved',
    'rejected',
    'reported',
    'pending_review',
    'removed'
  )),
  -- Machine reason (e.g. 'wrong_place', 'nsfw', 'identifiable_face',
  -- 'low_quality', 'duplicate_phash'). Stable strings; the iOS layer maps
  -- these to localized copy when surfacing rejection notices.
  reject_reason text,
  -- Human-readable detail surfaced to the uploader inside the rejection
  -- push notification + status sheet. Generated by the moderation Edge
  -- Function (often from the GPT-4o vision describe output).
  reject_detail text,
  exif_lat double precision,
  exif_lng double precision,
  -- 8x8 average-hash (or larger DCT pHash); blob keeps things flexible.
  phash bytea,
  width int,
  height int,
  bytes int,
  reported_count int NOT NULL DEFAULT 0,
  csam_scanned_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz,
  removed_at timestamptz
);

-- Hot path: PlaceDetailSheet pulls approved photos for a single place
-- ordered by approval recency. Status filter keeps the index lean.
CREATE INDEX IF NOT EXISTS place_user_photos_place_status_idx
  ON public.place_user_photos (city_place_id, status, approved_at DESC);

-- For "my uploads" surface + per-user quota lookups (see Phase F.4).
CREATE INDEX IF NOT EXISTS place_user_photos_uploader_idx
  ON public.place_user_photos (uploader_user_id, created_at DESC);

-- Used by the Phase F.8 long-press → report flow + worker dashboards.
CREATE INDEX IF NOT EXISTS place_user_photos_pending_review_idx
  ON public.place_user_photos (status, created_at DESC)
  WHERE status IN ('pending_moderation', 'pending_review', 'reported');

ALTER TABLE public.place_user_photos ENABLE ROW LEVEL SECURITY;

-- Public can read approved photos. Anon access is intentional: thumbnails
-- are served via CDN URLs, but anything calling the table directly (e.g.
-- the iOS PlaceDetailSheet) gets only what's been promoted.
CREATE POLICY place_user_photos_public_read_approved ON public.place_user_photos
  FOR SELECT USING (status = 'approved');

-- Uploaders can also see their own non-approved rows (so we can surface
-- "still under review" / "rejected because…" states in the UI).
CREATE POLICY place_user_photos_self_read ON public.place_user_photos
  FOR SELECT USING (uploader_user_id = auth.uid());

-- Inserts only allowed for the authenticated uploader. Status is forced
-- to 'pending_moderation' on the client; the moderation Edge Function
-- (service role) is the only writer past that point.
CREATE POLICY place_user_photos_self_insert ON public.place_user_photos
  FOR INSERT WITH CHECK (
    uploader_user_id = auth.uid()
    AND status = 'pending_moderation'
  );

GRANT SELECT ON public.place_user_photos TO anon, authenticated;
GRANT INSERT ON public.place_user_photos TO authenticated;

-- ---------------------------------------------------------------------------
-- known_bad_phashes — perceptual-hash denylist
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.known_bad_phashes (
  phash bytea PRIMARY KEY,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.known_bad_phashes ENABLE ROW LEVEL SECURITY;
-- No public policies. Only service-role workers (the moderation function +
-- ops console) read/write this table.

-- ---------------------------------------------------------------------------
-- dsa_appeals — EU DSA notice-and-action audit log
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.dsa_appeals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  photo_id uuid NOT NULL REFERENCES public.place_user_photos (id) ON DELETE CASCADE,
  uploader_user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  appeal_text text,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'accepted', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

CREATE INDEX IF NOT EXISTS dsa_appeals_status_idx
  ON public.dsa_appeals (status, created_at DESC)
  WHERE status = 'open';

CREATE INDEX IF NOT EXISTS dsa_appeals_photo_idx
  ON public.dsa_appeals (photo_id);

ALTER TABLE public.dsa_appeals ENABLE ROW LEVEL SECURITY;

-- An uploader sees only their own appeals.
CREATE POLICY dsa_appeals_self_read ON public.dsa_appeals
  FOR SELECT USING (uploader_user_id = auth.uid());

-- An uploader can file an appeal but cannot mutate its status (that's
-- service role only, via the human-moderation Edge Function).
CREATE POLICY dsa_appeals_self_insert ON public.dsa_appeals
  FOR INSERT WITH CHECK (
    uploader_user_id = auth.uid()
    AND status = 'open'
  );

GRANT SELECT, INSERT ON public.dsa_appeals TO authenticated;

-- ---------------------------------------------------------------------------
-- Storage buckets — quarantine (private) + public (CDN-served)
-- ---------------------------------------------------------------------------
--
-- We create the buckets up-front so the iOS background URLSession upload
-- can target a known-good path on day one. Bucket creation is idempotent;
-- the Storage RLS policies live on `storage.objects` and are scoped per
-- bucket via the `bucket_id` column.

INSERT INTO storage.buckets (id, name, public)
VALUES ('place-photos-quarantine', 'place-photos-quarantine', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('place-photos-public', 'place-photos-public', true)
ON CONFLICT (id) DO NOTHING;

-- Quarantine bucket: authenticated users can upload to a path namespaced
-- by their uid (`<uid>/<photo_id>.jpg`). They can read back their own
-- pending photos so the iOS sheet can render "still uploading" previews
-- without waiting for promotion.
DROP POLICY IF EXISTS place_photos_quarantine_self_insert ON storage.objects;
CREATE POLICY place_photos_quarantine_self_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'place-photos-quarantine'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS place_photos_quarantine_self_read ON storage.objects;
CREATE POLICY place_photos_quarantine_self_read ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'place-photos-quarantine'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Public bucket: anonymous read is the entire point. No client-side write
-- policies; only the moderation Edge Function (service role) ever writes
-- to it via the move-on-promotion path.
DROP POLICY IF EXISTS place_photos_public_read ON storage.objects;
CREATE POLICY place_photos_public_read ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'place-photos-public');
