//
//  TripExpense.swift
//  wayfind
//
//  One row in `trip_expenses`. Monetary fields use `Decimal` end-to-end —
//  the PostgREST codec encodes/decodes them as String so we never lose
//  precision through Double. The `isAutoSynced` flag is the contract with
//  the booking → expense auto-sync trigger: rows it created stay in lock
//  step with the booking until a user edits them, at which point the trigger
//  flips the flag back to `false` and stops touching the row.
//

import Foundation

struct TripExpense: Identifiable, Hashable, Sendable {
    let id: UUID
    let tripId: UUID
    /// Creator of the expense row. May be nil on legacy rows.
    let userId: UUID?
    /// Whoever actually paid. We use this — not `userId` — for "you paid X"
    /// math in the settlements ledger.
    let payerUserId: UUID?
    /// Linked booking when this row was generated by `tg_sync_booking_expense`
    /// (or the same flow on the email-import path). `nil` for hand-entered
    /// expenses. `ON DELETE SET NULL` so deleting the booking detaches the
    /// expense rather than nuking the user's own ledger.
    let bookingId: UUID?
    let title: String
    let amount: Decimal
    let currencyCode: String
    let category: ExpenseCategory
    /// `equal | exact | percentage | full`. We store this even for `full`
    /// (paid-by-one) so the editor can distinguish "split equally with one
    /// person" from "I'm covering this".
    let splitType: SplitType
    let expenseDate: Date
    let notes: String?
    let isAutoSynced: Bool
    let createdAt: Date?
    let updatedAt: Date?

    enum SplitType: String, Hashable, Sendable, CaseIterable, Codable {
        case equal
        case exact
        case percentage
        case full

        /// UX label shown in the segmented split picker. "Just me" reads
        /// better than "Full" in body copy.
        var displayLabel: String {
            switch self {
            case .equal: return "Equal"
            case .exact: return "Exact"
            case .percentage: return "Percent"
            case .full: return "Just me"
            }
        }

        static func from(rawValue raw: String?) -> SplitType {
            guard let raw, let match = SplitType(rawValue: raw.lowercased()) else {
                return .equal
            }
            return match
        }
    }
}


// =============================================================================
