//
//  TripExpense.swift
//  wayfind
//
//  One row in `trip_expenses`. Monetary fields use `Decimal` end-to-end —
//  the PostgREST codec encodes/decodes them as String so we never lose
//  precision through Double. The `isAutoSynced` flag is the contract with
//  the booking → expense auto-sync trigger: rows it created stay in lock
//  step with the booking until a user edits them, at which point the trigger
//  flips the flag back to `false` and stops touching the row.
//

import Foundation

struct TripExpense: Identifiable, Hashable, Sendable {
    let id: UUID
    let tripId: UUID
    /// Creator of the expense row. May be nil on legacy rows.
    let userId: UUID?
    /// Whoever actually paid. We use this — not `userId` — for "you paid X"
    /// math in the settlements ledger.
    let payerUserId: UUID?
    /// Linked booking when this row was generated by `tg_sync_booking_expense`
    /// (or the same flow on the email-import path). `nil` for hand-entered
    /// expenses. `ON DELETE SET NULL` so deleting the booking detaches the
    /// expense rather than nuking the user's own ledger.
    let bookingId: UUID?
    /// Groups multiple flight-booking legs (connecting/return) under one
    /// combined budget row. When non-nil, the expense represents the combined
    /// total across all bookings sharing this ID rather than a single booking.
    /// `nil` for all non-flight and single-leg entries.
    let bookingGroupId: UUID?
    let title: String
    /// Ledger amount in ``currencyCode`` (trip budget ISO). Equals the user’s
    /// typed total when that currency matches the trip cap; otherwise it is
    /// the trip-currency equivalent using ``fxRateAtCapture``.
    let amount: Decimal
    /// ISO 4217 for ``amount`` (normalized trip budget currency on new writes).
    let currencyCode: String
    /// Amount the user entered, in ``originalCurrencyCode``.
    let originalAmount: Decimal
    /// ISO 4217 for ``originalAmount``.
    let originalCurrencyCode: String
    /// Locked multiplier: `amount ≈ originalAmount * fxRateAtCapture` (rounded).
    let fxRateAtCapture: Decimal
    /// Effective quote date for ``fxRateAtCapture`` (mirrors `fx_rate_date`).
    let fxRateDate: Date
    let category: ExpenseCategory
    /// `equal | exact | percentage | full`. We store this even for `full`
    /// (paid-by-one) so the editor can distinguish "split equally with one
    /// person" from "I'm covering this".
    let splitType: SplitType
    let expenseDate: Date
    let notes: String?
    let isAutoSynced: Bool
    let createdAt: Date?
    let updatedAt: Date?

    enum SplitType: String, Hashable, Sendable, CaseIterable, Codable {
        case equal
        case exact
        case percentage
        case full

        /// UX label shown in the segmented split picker. "Just me" reads
        /// better than "Full" in body copy.
        var displayLabel: String {
            switch self {
            case .equal: return "Equal"
            case .exact: return "Exact"
            case .percentage: return "Percent"
            case .full: return "Just me"
            }
        }

        static func from(rawValue raw: String?) -> SplitType {
            guard let raw, let match = SplitType(rawValue: raw.lowercased()) else {
                return .equal
            }
            return match
        }
    }

    init(
        id: UUID,
        tripId: UUID,
        userId: UUID?,
        payerUserId: UUID?,
        bookingId: UUID?,
        bookingGroupId: UUID? = nil,
        title: String,
        amount: Decimal,
        currencyCode: String,
        category: ExpenseCategory,
        splitType: SplitType,
        expenseDate: Date,
        notes: String?,
        isAutoSynced: Bool,
        createdAt: Date?,
        updatedAt: Date?,
        originalAmount: Decimal? = nil,
        originalCurrencyCode: String? = nil,
        fxRateAtCapture: Decimal? = nil,
        fxRateDate: Date? = nil
    ) {
        self.id = id
        self.tripId = tripId
        self.userId = userId
        self.payerUserId = payerUserId
        self.bookingId = bookingId
        self.bookingGroupId = bookingGroupId
        self.title = title
        self.amount = amount
        let code = currencyCode.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
        self.currencyCode = code.isEmpty ? "USD" : String(code.prefix(PreferredCurrencyFormatting.codeMaxLength))
        self.category = category
        self.splitType = splitType
        self.expenseDate = expenseDate
        self.notes = notes
        self.isAutoSynced = isAutoSynced
        self.createdAt = createdAt
        self.updatedAt = updatedAt

        let origAmt = originalAmount ?? amount
        self.originalAmount = origAmt
        let origCurRaw = (originalCurrencyCode ?? currencyCode)
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased()
        self.originalCurrencyCode = origCurRaw.isEmpty
            ? self.currencyCode
            : String(origCurRaw.prefix(PreferredCurrencyFormatting.codeMaxLength))
        self.fxRateAtCapture = fxRateAtCapture ?? 1
        self.fxRateDate = fxRateDate ?? expenseDate
    }

    /// When true, show receipt-line (original) vs trip-ledger in budget rows.
    var isOriginalDistinctFromTripLedger: Bool {
        originalCurrencyCode != currencyCode
            || TripExpenseLedgerNormalizer.roundMoney2(originalAmount) != TripExpenseLedgerNormalizer.roundMoney2(amount)
    }

    /// User-visible origin of this expense row. Drives badge display and
    /// edit-confirmation copy on the budget screen.
    var provenance: Provenance {
        if let groupId = bookingGroupId {
            return .combinedFlight(groupId: groupId)
        }
        return bookingId != nil ? .bookingLinked : .manual
    }

    enum Provenance: Sendable, Hashable {
        /// Row is linked to a single `trip_bookings` record. Edits may write
        /// back to the booking amount (two-way sync). Badge: "Linked".
        case bookingLinked
        /// Row represents the combined total for a multi-leg or return flight
        /// itinerary. `groupId` ties the legs together in the DB.
        /// Badge: "Combined".
        case combinedFlight(groupId: UUID)
        /// Row was entered manually in the Add Expense sheet. Edits stay
        /// in budget only. No badge shown (manual is the implicit default).
        case manual
    }
}


// =============================================================================
